version: "3"
services:
  app:
    env_file:
      - .env
    container_name: clothesreviewhub
    build:
      dockerfile: Dockerfile
    command: "streamlit run --server.port 8501 --server.enableCORS false ClothesReviewHub.py"
    ports:
      - "8501:8501"
    image: clothesreviewhub:v1